### ISSUE TITLE
I have an issue when running it

### ISSUE THREAD

**Issue by abdul7397** [ehamiter/pyufc#1]
I get this error
`Traceback (most recent call last):
File "main.py", line 1, in <module>
from pyufc import Fighter
ImportError: cannot import name 'Fighter' from 'pyufc' (/home/container/.local/lib/python3.8/site-packages/pyufc/__init__.py)
`

**Comment by ehamiter** [comment]
Sorry about that-- ufc.com changed their layout so this package unfortunately no longer works. I'll update the README to reflect that.
